blueprints/auth.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_mail import Message
import random
import string

from models import User
from utils.token import get_token
from exts import mail # 导入 mail 对象
from .form import registerForm, loginForm
# 创建蓝图对象
auth = Blueprint( 'auth', __name__, url_prefix='/auth' )


@auth.route( '/mail/' )
def mail_test():
    message = Message( subject='Hello', recipients=['3446373836@qq.com'], body='你好，这是一封测试邮件' )
    mail.send( message )
    return '邮件发送成功'


@auth.route('/send_code/', methods=['GET', 'POST'])
def send_code():
    # 获取邮箱地址
    email = request.args.get('email')
    # 生成随机六位验证码
    code = ''.join(random.choices(string.digits, k=6))
    message = Message(subject='验证码', recipients=[email], body=f'您好，您的验证码为：{code}')
    mail.send(message)
    # 将验证码存储到 session 中 / memcache 中 / redis 中
    session['code'] = code
    return '邮件发送成功'

# 注册页面
@auth.route( '/register/', methods=['POST', "GET"] )
def register():
    if request.method == 'POST':
        form = registerForm(request.form)
        if form.validate():
            username = request.form['username']
            password = request.form['password']  # 密码需要加密存储
            email = request.form['email']
            payload = {'username': username, 'password': generate_password_hash(password)}
            token = get_token(payload)
            data = {'username': username,
                    "email": email,
                    'password': generate_password_hash(password),
                    'token': token
                    }

            User.save(data)
            flash('用户注册成功')
            return redirect(url_for('login'))
        else:
            [flash(error[0]) for error in form.errors.values()]
            return redirect(request.referrer)

    else:  # 如果是 GET 请求
        return render_template( 'register.html' )


# 登录页面
@auth.route( '/login/', methods=['POST', 'GET'] )
def login():
    print( request.method )
    if request.method == 'POST':
        form = loginForm(request.form)
        if form.validate():
            username = request.form['username']
            password = request.form['password']
            user = User.getUser({'username': username})
            if not user or not check_password_hash(user.password, password):
                flash('用户名或密码无效')
            else:
                # cookie 适合存储少量数据,一般用来存放登录授权
                session['user_id'] = user._id



            # session['user_id'] =
        #     if 'is_admin' in user_data:
        #         flash("管理员已登录")
        #         # return render_template('hello.html', username=username,user_data=user_data)
        #         return redirect(url_for('hello', username=username))
        #     else:
        #
        #         return redirect(url_for('hello', username=username))
        # else:
        #     [flash(error[0]) for error in form.errors.values()]
                return redirect(url_for('qa.index'))
    else:  # 如果是 GET 请求
        return render_template( 'login.html')

@auth.route('/logout/')
def logout():
    session.pop('user_id', None)
    return redirect(request.referrer)

blueprints/order.py
from flask import Blueprint, render_template, request, redirect, url_for, flash


order= Blueprint('order', __name__,url_prefix='/order' )

@order.route('/', methods=['GET', 'POST'])
def index():
    return render_template('order.html')

blueprints/qa.py
from bson import ObjectId
from flask import Blueprint, render_template, request, redirect, url_for, g, jsonify
from datetime import datetime
from bson.regex import Regex

from .form import ArticleForm, CommentForm
from models import Article, Comment
from decorators import login_required

qa = Blueprint('qa', __name__, url_prefix='/qa')

# 首页
@qa.route('/')
def index():
    articles = Article.getArticles()
    return render_template('index.html', articles=articles)

# 查看文章详情
@qa.route('/article', methods=['GET', 'POST'])
def article():
    article_id = request.args.get('id')
    article = Article.getArticleById(ObjectId(article_id))
    return render_template('article_detail.html', article=article)

# 发表文章
@qa.route('/article/edit', methods=['GET', 'POST'])
@login_required
def article_edit():
    if request.method == 'POST':
        form = ArticleForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            article_data = {
                "title": title,
                "content": content,
                "create_time": datetime.now(),
                "author": g.user.username,
                "author_id": g.user._id
            }
            Article.save(article_data)
            return redirect(url_for('qa.index'))
        else:
            return jsonify(errors=form.errors)
    else:
        return render_template('article.html')

# 发表评论
@qa.route('/article/comment', methods=['POST'])
@login_required
def article_comment():
    form = CommentForm(request.form)
    if form.validate():
        content = form.content.data
        article_id = form.article_id.data
        comment_data = {
            "content": content,
            "create_time": datetime.now(),
            # "author": g.user.username,
            "author_id": g.user._id,
            "article_id": ObjectId(article_id)
        }
        Comment.save(comment_data)
        return redirect(url_for('qa.article', id=article_id))
    else:
        form.errors

        return redirect(request.referrer)

# 搜索文章
@qa.route('/search', methods=['GET', 'POST'])
def search():
    keyword = request.args.get('keyword')
    if keyword:
        # 构造正则表达式以匹配包含关键字的文章标题
        regex = Regex(keyword, 'i')  # 'i' 表示不区分大小写

        # 使用正则表达式执行查询
        articles = Article.getArticles({"title": {"$regex": regex}})

        # 返回包含关键字的文章列表
        return render_template('index.html', articles=articles)
    else:
        # 如果没有提供关键字，则返回空结果
        return redirect(request.referrer)

templates/article.html
{% extends 'base.html' %}

{% block head %}
    <script src="{{ url_for('static',filename='js/article.js') }}"></script>

{% endblock %}

{% block title %}发表问答{% endblock %}

{% block body %}

    <h3 class="page-title">发表问答</h3>
    <form id="article-form" action="{{ url_for('qa.article_edit') }}" method="post">
        <div class="form-container">
            <div class="form-group">
                <input name="title" type="text" placeholder="请输入标题" class="form-control">
            </div>
            <div class="form-group">
                <textarea name="content" placeholder="请输入内容" id="" class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">提交</button>
            </div>
        </div>
    </form>

{% endblock %}

templates/article_detail.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/article_detail.css') }}">
{% endblock %}

{% block title %}详情{% endblock %}

{% block body %}
    <div class="main">
        <h3 class="page-title">{{ article.title }}</h3>
        <p class="article-info">
            <span>作者：{{ article.author }}</span>
            <span>时间：{{ article.create_time|dformat }}</span>
        </p>
        <hr>
        {#        文本超出宽度时自动换行，并保留原格式#}
        <pre class="article-content " style="white-space: pre-wrap;">{{ article.content }}</pre>
        <hr>
        <h4 class="comment-group-title">评论（{{ article.comments|length }}）：</h4>
        <form action="{{ url_for('qa.article_comment') }}" method="post" class="my-4">
            <input type="hidden" name="article_id" value="{{ article._id }}">
            <div class="form-row">
                <div class="col">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                </div>
                <div class="col-auto">
                    <button class="btn btn-primary">评论</button>
                </div>
            </div>
        </form>

        <ul class="comment-group">
            {% for comment in article.comments %}
                <li>
                    <div class="user-info">
                        <img class="avatar" src="{{ url_for('static',filename='images/boy.jpg') }}" alt="">
                        <span class="username">{{ comment.user.username }}</span>
                        <span class="create-time">{{ comment.create_time |dformat }}</span>
                    </div>
                    <p class="comment-content">{{ comment.content }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
    {#    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
    {#    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container" style="min-width: 540px">
        <a class="navbar-brand" href="#">
            <img class="logo rounded" src="{{ url_for('static',filename="images/photo.png") }}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('qa.index') }}">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('qa.article_edit') }}">发布问答</a>
                </li>
            </ul>
            <form class="form-inline" action="{{ url_for('qa.search') }}">
                <input name="keyword" type="text" class="form-control" placeholder="请输入关键字">
                <button type="submit" class="btn btn-outline-success">查找</button>
            </form>
            <ul class="navbar-nav ml-auto">
                {% if user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">注销</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}{% endblock %}
</body>
</html>

templates/hello.html
<script type="text/javascript"
        src="{{ url_for('static', filename = 'js/register.js') }}"></script>
{% extends "base.html" %}

{% block title %}主页面{% endblock %}
{% block body %}
    <h1 id="name">Hello {{ username }}!</h1>
    {#<h1>日期:{{ time|dformat }}</h1>#}
    <!--这里使用with语句将get_flashed_messages()函数的返回值赋给messages变量，该变量将包含所有闪现消息。-->
    <!--% if messages %：检查是否有闪现消息存在。-->
    <!--<ul class="flashes">：在HTML中创建一个无序列表，用于显示闪现消息。-->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                <!--遍历所有闪现消息 endfor结束消息遍历-->
                {% for message in messages %}
                    <!--对于每个消息，创建一个列表项（<li>标签）来显示消息内容。-->
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <!--结束条件判断 和with语句-->
        {% endif %}
    {% endwith %}
    <input type="button" onclick="sayHello()" value="Say Hello"/>
    {% if username %}
        <p>您已登录,<a href="{{ url_for('logout') }}">点击这里注销</a></p>
    {% else %}
        <p>您暂未登录,点击这里<a href="{{ url_for('login') }}"><b>登录</b></a></p>
    {% endif %}
{#    <form action="http://localhost:5000/score" method="POST">#}
{#        <p><label>分数</label><input type="submit" value="查询"/></p>#}
{#    </form>#}

    <table>
        <tr>
            <th>用户</th>
        </tr>
        {% for data in user_data %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ data.username }}</td>
                <td>
                    <form action="{{ url_for('delete', username=data.username) }}" method="post">
                        <button type="submit" >Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
    {#<form action="/setcookie" method="POST">#}
    {#    <label>ID</label>#}
    {#    <input type='text' name='name'/>#}
    {#    <input type='submit' value='提交'/>#}
    {#</form>#}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}
{% block title %}
    首页
{% endblock %}

{% block body %}
    <div class="main">
        <ul class="list-group">
            {% for article in articles %}
                <li class="list-group-item">
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        <div class="side-article">
                            <img class="side-article-avatar" src="{{ url_for('static',filename="images/boy.jpg") }}"
                                 alt="男孩">
                        </div>
                        <div class="article-main">
                            <h5 class="mb-1"><a href="{{ url_for('qa.article',id=article._id) }}">{{ article.title }}</a></h5>
                            <p class="article-content">{{ article.content | truncate(100) }}</p>
                            <small class="d-flex justify-content-between align-items-center">
                                <span class="article-author">{{ article.author }}</span>
                                <span class="article-time">{{ article.create_time | dformat }}</span>
                            </small>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block body %}
<div class="container" style="width: 30%">
    <h1 class="mt-5">登录</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <form name="loginForm" action="{{ url_for('auth.login') }}" class="mt-3" method="POST">
        <div class="form-group">
            <label for="username">用户名/邮箱</label>
            <input type="text" class="form-control" name="username" placeholder="请输入用户名/邮箱">
        </div>
        <div class="form-group">
            <label for="password">密码:</label>
            <input type="password" class="form-control" name="password" placeholder="请输入密码">
        </div>

        <div class="input-group mb-3 d-flex justify-content-between">
            <a href="{{ url_for('auth.register') }}" class="btn btn-primary">注册</a>
            <button type="submit" class="btn btn-primary">登录</button>
        </div>
        {#<form action="/login" method="POST">#}
        {#    <label>用户名</label><input type='text' name='username' /><br><br>#}
        {#    <label>密码：</label><input type="password" name='password' required="required" ><br><br>#}
        {#    <a href = "{{ url_for('register') }}"><b>注册</b></a>#}
        {#    <input type='submit' value='登录'/>#}
        {#</form>#}
    </form>
</div>
{% endblock %}

templates/order.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>淘宝数据分析可视化系统</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <style>
        /* 自定义样式可以在这里添加 */
    </style>
</head>

<body>
    <div class="container-fluid" >
        <div class="row " >
            <!-- 导航选择栏 -->
            <div class="col-md-auto bg-light p-3 text-center min-vh-100">
                <h3 class="mt-3 m-3"><a class="text-decoration-none" href="https://www.example.com">首页</a></h3>
                <ul class="nav flex-column mt-4 m-3">
                    <li class="nav-item">
                        <a class="nav-link active" href="#user-behavior">用户行为分析</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#product-analysis">商品分析</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#time-analysis">时间分析</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#category-analysis">商品类别分析</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#user-analysis">用户分析</a>
                    </li>
                </ul>
            </div>
            <!-- 可视化界面 -->
            <div class="col-md-9">
                <!-- 上半部分标题 -->
                <div class="mt-3">
                    <h5 >淘宝数据分析可视化系统</h5>
                </div>
                <!-- 下半部分可视化界面，使用相应的ID来定位导航 -->
                <div id="user-behavior" class="mt-5">
                    <!-- 用户行为分析内容 -->
                    <!-- 这里放置用户行为分析的可视化内容 -->
                </div>
                <div id="product-analysis" class="mt-5">
                    <!-- 商品分析内容 -->
                    <!-- 这里放置商品分析的可视化内容 -->
                </div>
                <div id="time-analysis" class="mt-5">
                    <!-- 时间分析内容 -->
                    <!-- 这里放置时间分析的可视化内容 -->
                </div>
                <div id="category-analysis" class="mt-5">
                    <!-- 商品类别分析内容 -->
                    <!-- 这里放置商品类别分析的可视化内容 -->
                </div>
                <div id="user-analysis" class="mt-5">
                    <!-- 用户分析内容 -->
                    <!-- 这里放置用户分析的可视化内容 -->
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/question.html
{% extends 'base.html' %}

{% block head %}

    <link rel="stylesheet" href="{{ url_for('static',filename='css/question.css') }}">
{% endblock %}

{% block title %}发表问答{% endblock %}

{% block body %}

    <h3 class="page-title">发表问答</h3>
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <input name="title" type="text" placeholder="请输入标题" class="form-control">
            </div>
            <div class="form-group">
                <textarea name="content" placeholder="请输入内容" id="" class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">提交</button>
            </div>
        </div>
    </form>

{% endblock %}

templates/readcookie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cookie</title>
</head>
<body>
    <p>Cookies已经设置完成!</p>
    <p>请点击<a href="/getcookie">这里查看</a></p>
</body>
</html>

{#{% extends "base.html" %}#}
{##}
{#{% block head %}#}
{#<script type="text/javascript" src="{{ url_for('static', filename = 'js/order.js') }}"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>#}
{#<link rel="stylesheet" href="{{ url_for('static', filename = 'css/search.css') }}">#}
{#{% endblock %}#}
{##}
{#{% block title %}订单{% endblock %}#}
{##}
{#{% block body %}#}
{#    <div class="div_search">#}
{#        <input type="text" id="orderNumber" class="form-control" placeholder="请输入用户名">#}
{#        <button id="searchButton" class="btn btn-primary" onclick="searchOrder()">查询订单</button>#}
{#    </div>#}
{#    <canvas id="myChart" width="400" height="400"></canvas>#}
{#    <canvas id="weeklyOrdersChart" width="400" height="400"></canvas>#}
{##}
{#    <div id="orderResult"></div>#}
{#    <div id="orderStats"></div>#}
{##}
{#{% endblock %}#}

templates/register.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/register.js') }}"></script>
{% endblock %}
{% block title %}注册{% endblock %}

{% block body %}
    <div class="container" style="width: 30%">
        <h1 class="mt-5">注册</h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <form name="registerForm" action="{{ url_for('auth.register') }}" class="mt-3" method="POST">
            <div class="form-group">
                <label for="username">用户名:</label>
                <input type="text" class="form-control" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">密码:</label>
                <input type="password" class="form-control" name="password" required>
            </div>
            <div class="form-group">
                <label for="password_confirmation">确认密码:</label>
                <input type="password" class="form-control" name="password_confirmation" required>
            </div>
            <div class="form-group">
                <label for="Email">邮箱</label>
                <input type="text" class="form-control" name="email" required>
            </div>
            <div class="form-group">
                <label for="identifying_code">验证码:</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="identifying_code" required>
                    <div class="input-group-append">
                        <button id="sendCodeBtn" type="button" class="btn btn-primary" onclick="sendIdentifyingCode()">
                            发送验证码
                        </button>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">注册</button>
        </form>
    </div>
    {#<form name="registerForm" action="/register/" onsubmit="return validateForm()" method="POST">#}
    {#    <p><label>用户名:</label><input type='text' name='username'/></p>#}
    {#    <p><label>密码:</label><input type="password" name='password'></p>#}
    {#    <p><label>确认密码:</label><input type="password" name='password_confirmation'></p>#}
    {#    <p><label>Email:</label><input tpye="text" name="email"></p>#}
    {#    <input type='submit' value='注册'/>#}
    {#</form>#}
{% endblock %}

templates/score.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript" src="{{ url_for('static', filename = 'js/register.js') }}"></script>
{% endblock %}

{% block title %}
    分数
{% endblock %}
{% block body %}
    <h1>Score Data</h1>
    <h1>Hello {{ name }}!</h1>
    <form id="myForm" action="http://localhost:5000/submit" onsubmit="return submitForm()" method="POST">
        <p>输入姓名:</p>
        <input type="text" name="name" id="nameInput" value=""/>
        <input type="submit" value="提交"/>
    </form>
    <br>
    <table border="1">
        <tr>
            <th>Num</th>
            <th>ID</th>
            <th>Name</th>
            <th>Age</th>
            <th>Province</th>
            <th>Subjects</th>
        </tr>
        {% for record in student_data %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ record._id }}</td>
                <td>{{ record.name }}</td>
                <td>{{ record.age }}</td>
                <td>{{ record.province }}</td>
                <td>
                    <ul>
                        {% for subject in record.subject %}
                            <li>{{ subject.name }}: {{ subject.score }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}